// Materials / Procurement List Module
import { EngineInput, MaterialQuantities, BudgetResult, ProcurementItem } from '../types';
import { UNIT_RATES_PREMIUM, MATERIAL_QUALITY_MULTIPLIER } from '../data/qualityTiers';

export function generateProcurementList(
  input: EngineInput,
  qty: MaterialQuantities,
  budget: BudgetResult
): ProcurementItem[] {
  const { qualityTier, materialBrands } = input;
  const m = MATERIAL_QUALITY_MULTIPLIER[qualityTier];
  const r = UNIT_RATES_PREMIUM;

  const items: ProcurementItem[] = [
    // ── Structure ──
    {
      id: 'proc-1',
      trade: 'Structure',
      item: 'TMT Steel Bars Fe 550D',
      brand: materialBrands.steel,
      specification: 'IS 1786 certified, CRS (Corrosion Resistant Steel)',
      quantity: qty.steelTonnes,
      unit: 'Tonne',
      unitRate: Math.round(r.tmtSteelPerTonne * m.structural),
      totalCost: Math.round(qty.steelTonnes * r.tmtSteelPerTonne * m.structural),
      supplierNote: 'Order 5% extra as site waste. Demand mill test certificate.',
      leadTimeDays: 3,
    },
    {
      id: 'proc-2',
      trade: 'Structure',
      item: 'OPC 53 Grade Cement',
      brand: materialBrands.cement,
      specification: 'IS 269 OPC 53 grade, 3-month shelf life',
      quantity: qty.cementBags,
      unit: 'Bags (50 kg)',
      unitRate: Math.round(r.cement50kgBag * m.structural),
      totalCost: Math.round(qty.cementBags * r.cement50kgBag * m.structural),
      supplierNote: 'Procure in lots of 200 bags. Store on raised wooden pallets.',
      leadTimeDays: 1,
    },
    {
      id: 'proc-3',
      trade: 'Structure',
      item: 'M25 Ready Mix Concrete',
      brand: 'UltraTech / ACC RMC Plant',
      specification: 'Design mix M25, 120mm slump, 28-day cube test',
      quantity: qty.concreteCuM,
      unit: 'Cu M',
      unitRate: Math.round(r.rmc25PerCuM * m.structural),
      totalCost: Math.round(qty.concreteCuM * r.rmc25PerCuM * m.structural),
      supplierNote: 'Book transit mixer 48 hours in advance for slab pours.',
      leadTimeDays: 2,
    },
    {
      id: 'proc-4',
      trade: 'Structure',
      item: 'AAC Blocks 150mm (6 inch)',
      brand: 'Birla Aerocon Grade 1',
      specification: 'IS 2185 Part 3, density 600-650 kg/m3',
      quantity: Math.round(qty.aacBlocksCuM * 0.55),
      unit: 'Cu M',
      unitRate: Math.round(r.aacBlock6InchPerCuM * m.structural),
      totalCost: Math.round(qty.aacBlocksCuM * 0.55 * r.aacBlock6InchPerCuM * m.structural),
      supplierNote: 'Use thin-bed polymer mortar; order adhesive with blocks.',
      leadTimeDays: 3,
    },
    {
      id: 'proc-5',
      trade: 'Structure',
      item: 'Washed River / Manufactured Sand',
      brand: 'Karnataka Licensed Quarry',
      specification: 'Zone II M-Sand, double washed, silt < 4%',
      quantity: qty.sandCuFt,
      unit: 'Cu Ft',
      unitRate: Math.round(r.sandPerCuFt),
      totalCost: Math.round(qty.sandCuFt * r.sandPerCuFt),
      supplierNote: 'Check Form C permit. Store away from cement.',
      leadTimeDays: 2,
    },

    // ── Flooring ──
    {
      id: 'proc-6',
      trade: 'Flooring',
      item: 'Vitrified Floor Tiles (4×2 ft)',
      brand: materialBrands.flooring,
      specification: 'Double charged, E1 slip resist, ≤0.5% water absorption',
      quantity: Math.round(qty.floorTilesSqFt * 0.7),
      unit: 'Sq Ft',
      unitRate: Math.round(r.vitrifiedTilePerSqFt * m.finishing),
      totalCost: Math.round(qty.floorTilesSqFt * 0.7 * r.vitrifiedTilePerSqFt * m.finishing),
      supplierNote: 'Order 8% extra for cuts and waste. Same batch number.',
      leadTimeDays: 5,
    },
    {
      id: 'proc-7',
      trade: 'Flooring',
      item: 'Bathroom & Kitchen Anti-skid Tiles',
      brand: 'Johnson Endura / RAK Ceramics',
      specification: 'R11 slip resistance rating, 300×300mm format',
      quantity: Math.round(qty.floorTilesSqFt * 0.15),
      unit: 'Sq Ft',
      unitRate: Math.round(85 * m.finishing),
      totalCost: Math.round(qty.floorTilesSqFt * 0.15 * 85 * m.finishing),
      supplierNote: '10% wastage buffer for bathroom cuts.',
      leadTimeDays: 3,
    },
    {
      id: 'proc-8',
      trade: 'Flooring',
      item: 'Bathroom Wall Tiles (2×1 ft)',
      brand: 'Kajaria Glamour Collection',
      specification: 'Satin wall tile, 600×300mm format',
      quantity: qty.wallTilesSqFt,
      unit: 'Sq Ft',
      unitRate: Math.round(r.wallTilePerSqFt * m.finishing),
      totalCost: Math.round(qty.wallTilesSqFt * r.wallTilePerSqFt * m.finishing),
      supplierNote: 'Verify layout drawing before ordering for cuts.',
      leadTimeDays: 4,
    },
    {
      id: 'proc-9',
      trade: 'Flooring',
      item: 'Black Granite Steps (20mm)',
      brand: 'Jet Black Sadahalli Granite',
      specification: '20mm polished slab, bullnose edge, 3 anti-skid grooves',
      quantity: qty.graniteSlabsSqFt,
      unit: 'Sq Ft',
      unitRate: Math.round(r.graniteStepPerSqFt * m.finishing),
      totalCost: Math.round(qty.graniteSlabsSqFt * r.graniteStepPerSqFt * m.finishing),
      supplierNote: 'Get quarry certificate. Machine cut grooves at workshop.',
      leadTimeDays: 7,
    },

    // ── Electrical ──
    {
      id: 'proc-10',
      trade: 'Electrical',
      item: 'FRLS Copper Electrical Wire',
      brand: materialBrands.electrical,
      specification: 'IS 694 FRLS PVC insulated copper, 1.5/2.5/4.0 sqmm',
      quantity: qty.electricalWireMetres,
      unit: 'Metres',
      unitRate: Math.round(r.wirePerMetre * m.mep),
      totalCost: Math.round(qty.electricalWireMetres * r.wirePerMetre * m.mep),
      supplierNote: 'Demand ISI mark and batch test certificate from supplier.',
      leadTimeDays: 2,
    },
    {
      id: 'proc-11',
      trade: 'Electrical',
      item: 'Modular Switches & Socket Plates',
      brand: materialBrands.electrical,
      specification: 'Glass / ABS finish, 16A sockets, child safe shutters',
      quantity: qty.switchModules,
      unit: 'Modules',
      unitRate: Math.round(r.switchModulePerUnit * m.mep),
      totalCost: Math.round(qty.switchModules * r.switchModulePerUnit * m.mep),
      supplierNote: 'Confirm layout drawing before final ordering.',
      leadTimeDays: 3,
    },

    // ── Plumbing ──
    {
      id: 'proc-12',
      trade: 'Plumbing',
      item: 'CPVC SDR11 Supply Pipes & Fittings',
      brand: 'Astral CPVC Pro',
      specification: 'SDR 11, rated 82°C at 28 bar, IS 15778',
      quantity: qty.cpvcSupplyMetres,
      unit: 'Metres',
      unitRate: Math.round(r.cpvcPipePerMetre * m.mep),
      totalCost: Math.round(qty.cpvcSupplyMetres * r.cpvcPipePerMetre * m.mep),
      supplierNote: 'Include elbow/tee fittings at 1.4× pipe cost.',
      leadTimeDays: 2,
    },
    {
      id: 'proc-13',
      trade: 'Plumbing',
      item: 'SWR Soil & Waste Drain Pipes',
      brand: 'Supreme / Prince SWR',
      specification: 'IS 14735 Type B SWR ring-fit rubber seal',
      quantity: qty.swrDrainMetres,
      unit: 'Metres',
      unitRate: Math.round(r.swrPipePerMetre * m.mep),
      totalCost: Math.round(qty.swrDrainMetres * r.swrPipePerMetre * m.mep),
      supplierNote: 'Order 110mm + 75mm mix in 60:40 ratio.',
      leadTimeDays: 2,
    },
    {
      id: 'proc-14',
      trade: 'Sanitary',
      item: 'CP Bathroom Fixture Sets',
      brand: materialBrands.bathroom,
      specification: 'Wall-hung WC + concealed cistern + thermostatic shower + basin',
      quantity: qty.bathroomFixtureSets,
      unit: 'Sets',
      unitRate: Math.round(r.bathroomSetPerUnit * m.fixtures),
      totalCost: Math.round(qty.bathroomFixtureSets * r.bathroomSetPerUnit * m.fixtures),
      supplierNote: 'Place order 6 weeks before fitting – long lead time item.',
      leadTimeDays: 42,
    },

    // ── Paints ──
    {
      id: 'proc-15',
      trade: 'Paint',
      item: 'Interior Luxury Emulsion Paint',
      brand: materialBrands.paint,
      specification: 'Teflon enriched washable emulsion, sheen finish',
      quantity: Math.ceil(qty.interiorPaintAreaSqFt / 45),
      unit: 'Litres',
      unitRate: Math.round(r.interiorPaintPerLitre * m.finishing),
      totalCost: Math.round(Math.ceil(qty.interiorPaintAreaSqFt / 45) * r.interiorPaintPerLitre * m.finishing),
      supplierNote: 'Procure from authorized dealer. Keep invoice for warranty.',
      leadTimeDays: 1,
    },
    {
      id: 'proc-16',
      trade: 'Paint',
      item: 'Exterior Weatherproof Emulsion',
      brand: 'Asian Paints Apex Ultima',
      specification: 'DPUR silicone technology, 7-year weatherproof warranty',
      quantity: Math.ceil(qty.exteriorPaintAreaSqFt / 60),
      unit: 'Litres',
      unitRate: Math.round(r.exteriorPaintPerLitre * m.finishing),
      totalCost: Math.round(Math.ceil(qty.exteriorPaintAreaSqFt / 60) * r.exteriorPaintPerLitre * m.finishing),
      supplierNote: 'Apply only when rain-free window ≥ 8 hours.',
      leadTimeDays: 1,
    },

    // ── Joinery ──
    {
      id: 'proc-17',
      trade: 'Joinery',
      item: 'Main Entrance Teak Door',
      brand: materialBrands.doors,
      specification: '45mm Burma teak, carved panel, SS hinges, 3-bolt lock',
      quantity: qty.mainDoorsCount,
      unit: 'Sets',
      unitRate: Math.round(r.mainDoorPerSet * m.joinery),
      totalCost: Math.round(qty.mainDoorsCount * r.mainDoorPerSet * m.joinery),
      supplierNote: 'Custom order: 6-8 week lead time. Get shop drawing approval.',
      leadTimeDays: 56,
    },
    {
      id: 'proc-18',
      trade: 'Joinery',
      item: 'UPVC Double Glazed Windows',
      brand: materialBrands.windows,
      specification: '60mm multichamber profile, 12mm argon-filled DGU, mosquito mesh',
      quantity: qty.windowAreaSqFt,
      unit: 'Sq Ft',
      unitRate: Math.round(r.upvcWindowPerSqFt * m.joinery),
      totalCost: Math.round(qty.windowAreaSqFt * r.upvcWindowPerSqFt * m.joinery),
      supplierNote: 'Factory measure after plaster is done. 3-4 week lead time.',
      leadTimeDays: 21,
    },
    {
      id: 'proc-19',
      trade: 'Joinery',
      item: 'Internal Flush Veneer Door Sets',
      brand: 'CenturyPly / Greenply',
      specification: 'BWP Grade marine ply, real veneer, mortise lock',
      quantity: qty.internalDoorsCount,
      unit: 'Sets',
      unitRate: Math.round(r.interiorDoorPerSet * m.joinery),
      totalCost: Math.round(qty.internalDoorsCount * r.interiorDoorPerSet * m.joinery),
      supplierNote: 'Allow 5mm clearance for flooring tile height.',
      leadTimeDays: 14,
    },

    // ── Waterproofing ──
    {
      id: 'proc-20',
      trade: 'Waterproofing',
      item: '2-Component Polymer Waterproofing',
      brand: 'Dr. Fixit Fastflex 2C / STP Roofdoc',
      specification: 'IS 6494 compliant, 2mm membrane, 48-hr pond test',
      quantity: qty.waterproofingAreaSqFt,
      unit: 'Sq Ft',
      unitRate: Math.round(r.waterproofingPerSqFt * m.finishing),
      totalCost: Math.round(qty.waterproofingAreaSqFt * r.waterproofingPerSqFt * m.finishing),
      supplierNote: 'Apply by manufacturer-trained applicator for warranty.',
      leadTimeDays: 2,
    },
  ];

  return items.filter((i) => i.quantity > 0 && i.totalCost > 0);
}
